[pytest]
testpaths=tests  # "My test files are inside the tests folder."So when you run:pytest - PyTest automatically looks inside: tests/
addopts= -v -s #This automatically adds: -v → verbose output -s → show print/log output - So you don't need to type: - pytest -v -s - every time. - You can simply use: pytest

